SELECT
RASCL AS NOME,
INDCL AS INDIRIZZO,
LOCCL AS COMUNE,
PROCL AS PROVINCIA,
CAPCL AS CAP,
NTECL AS TELEFONO,
CNOTE AS NOTE,
CDNAZ AS NAZIONE,
CDFIS AS CODICE_FISCALE,
FAXCL AS FAX
FROM ACG_DATV3.ANCL200F
WHERE CDCLI='@{codice}'