SELECT
DENUMO AS NUM_ORDINE,
DEDATA AS DATA_ORDINE,
DECLIE AS COD_CLIENTE,
DERIGA AS NUM_RIGA_ORDINE,
DERIAB AS STATO_LAVORAZIONE,
DESTAG AS STAGIONE,
DEMODE AS MODELLO,
DEARTI AS ARTICOLO,
DECOLO AS COLORE,
DESCAD AS SCALARINO,
DESTA2 AS STATO_ARTICOLO,
DEQT01 AS QTA01,
DEQT02 AS QTA02,
DEQT03 AS QTA03,
DEQT04 AS QTA04,
DEQT05 AS QTA05,
DEQT06 AS QTA06,
DEQT07 AS QTA07,
DEQT08 AS QTA08,
DEQT09 AS QTA09,
DEQT10 AS QTA10,
DEQT11 AS QTA11,
DEQT12 AS QTA12,
DENRCO AS NUM_COMMESSA,
DEDACO AS DATA_COMMESSA
FROM ABB_DATV3.ORDET00F
WHERE DETIPR='A'
AND DERIAB=20
AND DESTA2=''
