SELECT
MGANNO AS ANNO,
MGARTI AS ARTICOLO,
MGCOLO AS COLORE,
MGUNIM AS UNITA_MISURA,
MGGIAC AS GIACENZA,
MGIMPE AS IMPEGNATA,
MGORDI AS ORDINATA
FROM ABB_DATV3.MAGAZI01
WHERE MGANNO < 10
AND MGTIPO LIKE 'A'
AND MGCOMA LIKE 'M'
AND (MGGIAC - MGIMPE > 0 OR MGORDI > 0)
