SELECT
DESTAG AS STAGIONE,
DEMODE AS MODELLO,
DEARTI AS ARTICOLO,
DECOLO AS COLORE,
DESCAD AS SCALARINO,
DESTA2 AS STATO_ARTICOLO,
SUM(DEQT01) AS QTA0,
SUM(DEQT02) AS QTA1,
SUM(DEQT03) AS QTA2,
SUM(DEQT04) AS QTA3,
SUM(DEQT05) AS QTA4,
SUM(DEQT06) AS QTA5,
SUM(DEQT07) AS QTA6,
SUM(DEQT08) AS QTA7,
SUM(DEQT09) AS QTA8,
SUM(DEQT10) AS QTA9,
SUM(DEQT11) AS QTA10,
SUM(DEQT12) AS QTA11
FROM ABB_DATV3.ORDET00F
WHERE (DESTA2='1' OR DESTA2='2')
AND DETIPR LIKE 'A'
AND DECLIE='@{codiceCliente}'
GROUP BY DESTAG, DEMODE, DEARTI, DECOLO, DESCAD, DESTA2