SELECT
SSTAGI AS STAGIONE,
SMODEL AS MODELLO,
SARTIC AS ARTICOLO,
SCOLOR AS COLORE,
STAGLI AS DESCRIZIONE_TAGLIA,
SSCALA AS SCALARINO,
SUM(SQUANT) AS QTA
FROM ABB_DATV3.SALMOD
WHERE SCODMA='@{codiceMagazzino}'
AND SCLIDI=2
AND SQUANT>0
GROUP BY SSTAGI, SMODEL, SARTIC, SCOLOR, STAGLI, SSCALA